# Generated by Django 4.2.28 on 2026-03-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('Pagada', 'Pagada'), ('Pendiente', 'Pendiente'), ('Anulada', 'Anulada')], default='Pagada', max_length=20)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinica.cita')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.metodopago')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.paciente')),
            ],
        ),
    ]
