# Generated by Django 4.2.28 on 2026-03-26 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cita', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=20)),
                ('estado_cita', models.CharField(choices=[('Programada', 'Programada'), ('Asistida', 'Asistida'), ('Cancelada', 'Cancelada'), ('No Asistió', 'No Asistió')], default='Programada', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_personales', models.TextField(blank=True, null=True)),
                ('antecedentes_familiares', models.TextField(blank=True, null=True)),
                ('resumen_historial_ia', models.TextField(blank=True, help_text='Resumen global generado por IA para que el psicólogo lea el caso rápido.')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='usuarios.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=255)),
                ('enfoque_terapeutico', models.CharField(blank=True, max_length=100, null=True)),
                ('objetivos_tratamiento', models.TextField()),
                ('sugerencias_enfoque_ia', models.TextField(blank=True, help_text='Recomendaciones de la IA basadas en el diagnóstico y objetivos.')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado_tratamiento', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Suspendido', 'Suspendido'), ('Derivado', 'Derivado')], default='Activo', max_length=20)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.historialclinico')),
            ],
        ),
        migrations.CreateModel(
            name='EvolucionSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(help_text='Razón de la sesión de hoy')),
                ('estado_animo', models.CharField(choices=[('Aburrimiento', 'Aburrimiento'), ('Aceptacion', 'Aceptación'), ('Admiracion', 'Admiración'), ('Alegria', 'Alegría'), ('Alivio', 'Alivio'), ('Amor', 'Amor'), ('Ansiedad', 'Ansiedad'), ('Apatia', 'Apatía'), ('Asombro', 'Asombro'), ('Calma', 'Calma'), ('Culpa', 'Culpa'), ('Decepcion', 'Decepción'), ('Entusiasmo', 'Entusiasmo'), ('Frustracion', 'Frustración'), ('Gratitud', 'Gratitud'), ('Inseguridad', 'Inseguridad'), ('Ira', 'Ira'), ('Irritabilidad', 'Irritabilidad'), ('Miedo', 'Miedo'), ('Soledad', 'Soledad'), ('Tristeza', 'Tristeza')], max_length=30)),
                ('estresores_recientes', models.TextField(blank=True, help_text='Eventos vitales desde la última cita')),
                ('afecto_observado', models.CharField(choices=[('Congruente', 'Congruente con el relato'), ('Aplanado', 'Aplanado/Embotado'), ('Labil', 'Lábil (cambios bruscos)'), ('Incongruente', 'Incongruente')], default='Congruente', max_length=30)),
                ('nivel_energia', models.IntegerField(default=5, help_text='Escala del 1 al 10')),
                ('sueno_alterado', models.BooleanField(default=False)),
                ('apetito_alterado', models.BooleanField(default=False)),
                ('ideacion_suicida', models.BooleanField(default=False, verbose_name='¿Presenta ideación suicida?')),
                ('riesgo', models.CharField(choices=[('Riesgo Alto', 'Riesgo Alto'), ('Riesgo Medio', 'Riesgo Medio'), ('Riesgo Bajo', 'Riesgo Bajo'), ('Sin Riesgo', 'Sin Riesgo')], max_length=30)),
                ('descripcion_sesion', models.TextField(help_text='Detalle de lo ocurrido en la sesión')),
                ('evidencia', models.CharField(help_text='Signos clínicos que sustentan el diagnóstico', max_length=250)),
                ('diagnostico_sesion', models.CharField(blank=True, help_text='CIE-10 / DSM-5 o Hipótesis', max_length=255)),
                ('objetivo', models.CharField(max_length=200)),
                ('recomendaciones', models.TextField(blank=True)),
                ('proximo_paso', models.TextField(blank=True, help_text='Tareas o temas para la siguiente sesión', null=True)),
                ('analisis_sentimiento_ia', models.CharField(blank=True, help_text='Análisis automático de congruencia entre el relato y el afecto observado.', max_length=100)),
                ('resumen_ia', models.TextField(blank=True, help_text='Resumen ejecutivo estructurado por la IA.')),
                ('alertas_riesgo_ia', models.JSONField(blank=True, default=dict, help_text='Detección automática de palabras clave de riesgo en la descripción.')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evolucion', to='clinica.cita')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.tratamiento')),
            ],
        ),
    ]
