# Generated by Django 4.2.28 on 2026-04-10 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos'},
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='psicologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Especialista a Cargo'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='diagnostico',
            field=models.CharField(max_length=255, verbose_name='Diagnóstico Principal'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='clinica.historialclinico'),
        ),
    ]
